// Additional languages - use English as base with key translations
export const additionalLanguages = {
  es: { // Spanish
    nav: {
      home: "Inicio",
      courses: "Cursos",
      projects: "Proyectos",
      profile: "Perfil",
      login: "Iniciar",
      logout: "Salir",
    },
    home: {
      badge_text: "Aprende en 2-3 días · Crea con IA",
      hero_title: "Aprende a crear con IA",
      hero_subtitle: "Crea sitios web, aplicaciones y juegos con inteligencia artificial",
      cta_start: "Comenzar",
      cta_learn: "Saber más",
      tracks_title: "Elige tu camino",
      track_websites: "Sitios web",
      track_apps: "Aplicaciones",
      track_games: "Juegos",
      features_title: "¿Por qué nuestra plataforma?",
      feature_4_title: "Acceso de prueba",
      feature_4_desc: "3 lecciones gratis para empezar",
      projects_title: "Proyectos de estudiantes",
      view_project: "Ver proyecto",
    },
  },
  de: { // German
    nav: {
      home: "Startseite",
      courses: "Kurse",
      projects: "Projekte",
      profile: "Profil",
      login: "Anmelden",
      logout: "Abmelden",
    },
    home: {
      badge_text: "In 2-3 Tagen lernen · Mit KI erstellen",
      hero_title: "Lerne mit KI zu erstellen",
      hero_subtitle: "Erstelle Websites, Apps und Spiele mit künstlicher Intelligenz",
      cta_start: "Starten",
      cta_learn: "Mehr erfahren",
      tracks_title: "Wähle deinen Weg",
      track_websites: "Websites",
      track_apps: "Anwendungen",
      track_games: "Spiele",
      features_title: "Warum unsere Plattform?",
      feature_4_title: "Testzugang",
      feature_4_desc: "3 kostenlose Lektionen zum Einstieg",
      projects_title: "Studentenprojekte",
      view_project: "Projekt ansehen",
    },
  },
  fr: { // French
    nav: {
      home: "Accueil",
      courses: "Cours",
      projects: "Projets",
      profile: "Profil",
      login: "Connexion",
      logout: "Déconnexion",
    },
    home: {
      badge_text: "Apprends en 2-3 jours · Crée avec l'IA",
      hero_title: "Apprends à créer avec l'IA",
      hero_subtitle: "Crée des sites web, des applications et des jeux avec l'intelligence artificielle",
      cta_start: "Commencer",
      cta_learn: "En savoir plus",
      tracks_title: "Choisis ton chemin",
      track_websites: "Sites web",
      track_apps: "Applications",
      track_games: "Jeux",
      features_title: "Pourquoi notre plateforme?",
      feature_4_title: "Accès d'essai",
      feature_4_desc: "3 leçons gratuites pour démarrer",
      projects_title: "Projets d'étudiants",
      view_project: "Voir le projet",
    },
  },
  it: { // Italian
    nav: {
      home: "Home",
      courses: "Corsi",
      projects: "Progetti",
      profile: "Profilo",
      login: "Accedi",
      logout: "Esci",
    },
    home: {
      hero_title: "Impara a creare con l'IA",
      hero_subtitle: "Crea siti web, applicazioni e giochi con l'intelligenza artificiale",
      cta_start: "Inizia",
      cta_learn: "Scopri di più",
      track_websites: "Siti web",
      track_apps: "Applicazioni",
      track_games: "Giochi",
      features_title: "Perché la nostra piattaforma?",
      feature_4_title: "Accesso di prova",
      feature_4_desc: "3 lezioni gratuite per iniziare",
      projects_title: "Progetti degli studenti",
      view_project: "Vedi progetto",
    },
  },
  pt: { // Portuguese
    nav: {
      home: "Início",
      courses: "Cursos",
      projects: "Projetos",
      profile: "Perfil",
      login: "Entrar",
      logout: "Sair",
    },
    home: {
      hero_title: "Aprenda a criar com IA",
      hero_subtitle: "Crie sites, aplicativos e jogos com inteligência artificial",
      cta_start: "Começar",
      cta_learn: "Saber mais",
      track_websites: "Sites",
      track_apps: "Aplicativos",
      track_games: "Jogos",
      features_title: "Por que nossa plataforma?",
      feature_4_title: "Acesso experimental",
      feature_4_desc: "3 aulas grátis para começar",
      projects_title: "Projetos dos alunos",
      view_project: "Ver projeto",
    },
  },
  nl: { // Dutch
    nav: {
      home: "Home",
      courses: "Cursussen",
      projects: "Projecten",
      profile: "Profiel",
      login: "Inloggen",
      logout: "Uitloggen",
    },
    home: {
      hero_title: "Leer creëren met AI",
      hero_subtitle: "Maak websites, apps en games met kunstmatige intelligentie",
      cta_start: "Beginnen",
      cta_learn: "Meer weten",
      track_websites: "Websites",
      track_apps: "Applicaties",
      track_games: "Spellen",
      features_title: "Waarom ons platform?",
      feature_4_title: "Proeftoegang",
      feature_4_desc: "3 gratis lessen om te beginnen",
      projects_title: "Studentenprojecten",
      view_project: "Bekijk project",
    },
  },
  sv: { // Swedish
    nav: {
      home: "Hem",
      courses: "Kurser",
      projects: "Projekt",
      profile: "Profil",
      login: "Logga in",
      logout: "Logga ut",
    },
    home: {
      hero_title: "Lär dig skapa med AI",
      hero_subtitle: "Skapa webbplatser, appar och spel med artificiell intelligens",
      cta_start: "Börja",
      cta_learn: "Läs mer",
      track_websites: "Webbplatser",
      track_apps: "Appar",
      track_games: "Spel",
      features_title: "Varför vår plattform?",
      feature_4_title: "Provåtkomst",
      feature_4_desc: "3 gratis lektioner för att komma igång",
      projects_title: "Studentprojekt",
      view_project: "Se projekt",
    },
  },
  no: { // Norwegian
    nav: {
      home: "Hjem",
      courses: "Kurs",
      projects: "Prosjekter",
      profile: "Profil",
      login: "Logg inn",
      logout: "Logg ut",
    },
    home: {
      hero_title: "Lær å lage med AI",
      hero_subtitle: "Lag nettsteder, apper og spill med kunstig intelligens",
      cta_start: "Start",
      cta_learn: "Lær mer",
      track_websites: "Nettsteder",
      track_apps: "Apper",
      track_games: "Spill",
      features_title: "Hvorfor vår plattform?",
      feature_4_title: "Prøvetilgang",
      feature_4_desc: "3 gratis leksjoner for å komme i gang",
      projects_title: "Studentprosjekter",
      view_project: "Se prosjekt",
    },
  },
  da: { // Danish
    nav: {
      home: "Hjem",
      courses: "Kurser",
      projects: "Projekter",
      profile: "Profil",
      login: "Log ind",
      logout: "Log ud",
    },
    home: {
      hero_title: "Lær at skabe med AI",
      hero_subtitle: "Skab hjemmesider, apps og spil med kunstig intelligens",
      cta_start: "Start",
      cta_learn: "Læs mere",
      track_websites: "Hjemmesider",
      track_apps: "Apps",
      track_games: "Spil",
      features_title: "Hvorfor vores platform?",
      feature_4_title: "Prøveadgang",
      feature_4_desc: "3 gratis lektioner at starte med",
      projects_title: "Studenterprojekter",
      view_project: "Se projekt",
    },
  },
  fi: { // Finnish
    nav: {
      home: "Etusivu",
      courses: "Kurssit",
      projects: "Projektit",
      profile: "Profiili",
      login: "Kirjaudu",
      logout: "Kirjaudu ulos",
    },
    home: {
      hero_title: "Opi luomaan AI:n kanssa",
      hero_subtitle: "Luo verkkosivustoja, sovelluksia ja pelejä tekoälyn avulla",
      cta_start: "Aloita",
      cta_learn: "Lue lisää",
      track_websites: "Verkkosivustot",
      track_apps: "Sovellukset",
      track_games: "Pelit",
      features_title: "Miksi meidän alusta?",
      feature_4_title: "Kokeilukäyttö",
      feature_4_desc: "3 ilmaista oppituntia aloittamiseen",
      projects_title: "Opiskelijaprojektit",
      view_project: "Katso projekti",
    },
  },
  tr: { // Turkish
    nav: {
      home: "Ana Sayfa",
      courses: "Kurslar",
      projects: "Projeler",
      profile: "Profil",
      login: "Giriş",
      logout: "Çıkış",
    },
    home: {
      hero_title: "Yapay Zeka ile yaratmayı öğren",
      hero_subtitle: "Yapay zeka ile web siteleri, uygulamalar ve oyunlar oluştur",
      cta_start: "Başla",
      cta_learn: "Daha fazla öğren",
      track_websites: "Web siteleri",
      track_apps: "Uygulamalar",
      track_games: "Oyunlar",
      features_title: "Neden bizim platformumuz?",
      feature_4_title: "Deneme erişimi",
      feature_4_desc: "Başlamak için 3 ücretsiz ders",
      projects_title: "Öğrenci projeleri",
      view_project: "Projeyi gör",
    },
  },
  zh: { // Chinese
    nav: {
      home: "首页",
      courses: "课程",
      projects: "项目",
      profile: "个人资料",
      login: "登录",
      logout: "退出",
    },
    home: {
      hero_title: "学习使用AI创建",
      hero_subtitle: "使用人工智能创建网站、应用程序和游戏",
      cta_start: "开始",
      cta_learn: "了解更多",
      track_websites: "网站",
      track_apps: "应用",
      track_games: "游戏",
      features_title: "为什么选择我们的平台？",
      feature_4_title: "试用访问",
      feature_4_desc: "3节免费课程入门",
      projects_title: "学生项目",
      view_project: "查看项目",
    },
  },
  ja: { // Japanese
    nav: {
      home: "ホーム",
      courses: "コース",
      projects: "プロジェクト",
      profile: "プロフィール",
      login: "ログイン",
      logout: "ログアウト",
    },
    home: {
      hero_title: "AIで創造を学ぶ",
      hero_subtitle: "人工知能でウェブサイト、アプリ、ゲームを作成",
      cta_start: "始める",
      cta_learn: "詳細を見る",
      track_websites: "ウェブサイト",
      track_apps: "アプリ",
      track_games: "ゲーム",
      features_title: "なぜ当プラットフォーム？",
      feature_4_title: "トライアルアクセス",
      feature_4_desc: "無料レッスン3つで開始",
      projects_title: "学生プロジェクト",
      view_project: "プロジェクトを見る",
    },
  },
  ko: { // Korean
    nav: {
      home: "홈",
      courses: "과정",
      projects: "프로젝트",
      profile: "프로필",
      login: "로그인",
      logout: "로그아웃",
    },
    home: {
      hero_title: "AI로 만들기 배우기",
      hero_subtitle: "인공지능으로 웹사이트, 앱, 게임 만들기",
      cta_start: "시작하기",
      cta_learn: "더 알아보기",
      track_websites: "웹사이트",
      track_apps: "앱",
      track_games: "게임",
      features_title: "왜 우리 플랫폼인가?",
      feature_4_title: "체험 액세스",
      feature_4_desc: "시작을 위한 무료 레슨 3개",
      projects_title: "학생 프로젝트",
      view_project: "프로젝트 보기",
    },
  },
  ar: { // Arabic
    nav: {
      home: "الرئيسية",
      courses: "الدورات",
      projects: "المشاريع",
      profile: "الملف الشخصي",
      login: "تسجيل الدخول",
      logout: "تسجيل الخروج",
    },
    home: {
      hero_title: "تعلم الإنشاء بالذكاء الاصطناعي",
      hero_subtitle: "أنشئ مواقع وتطبيقات وألعاب بالذكاء الاصطناعي",
      cta_start: "ابدأ",
      cta_learn: "اعرف المزيد",
      track_websites: "المواقع",
      track_apps: "التطبيقات",
      track_games: "الألعاب",
      features_title: "لماذا منصتنا؟",
      feature_4_title: "وصول تجريبي",
      feature_4_desc: "3 دروس مجانية للبدء",
      projects_title: "مشاريع الطلاب",
      view_project: "عرض المشروع",
    },
  },
  hi: { // Hindi
    nav: {
      home: "होम",
      courses: "कोर्सेस",
      projects: "प्रोजेक्ट्स",
      profile: "प्रोफ़ाइल",
      login: "लॉगिन",
      logout: "लॉगआउट",
    },
    home: {
      hero_title: "AI के साथ बनाना सीखें",
      hero_subtitle: "कृत्रिम बुद्धिमत्ता से वेबसाइट, ऐप और गेम बनाएं",
      cta_start: "शुरू करें",
      cta_learn: "और जानें",
      track_websites: "वेबसाइट्स",
      track_apps: "ऐप्स",
      track_games: "गेम्स",
      features_title: "हमारा प्लेटफॉर्म क्यों?",
      feature_4_title: "ट्रायल एक्सेस",
      feature_4_desc: "शुरुआत के लिए 3 मुफ्त पाठ",
      projects_title: "छात्र परियोजनाएं",
      view_project: "प्रोजेक्ट देखें",
    },
  },
  th: { // Thai
    nav: {
      home: "หน้าแรก",
      courses: "คอร์ส",
      projects: "โปรเจค",
      profile: "โปรไฟล์",
      login: "เข้าสู่ระบบ",
      logout: "ออกจากระบบ",
    },
    home: {
      hero_title: "เรียนรู้การสร้างด้วย AI",
      hero_subtitle: "สร้างเว็บไซต์ แอป และเกมด้วยปัญญาประดิษฐ์",
      cta_start: "เริ่มต้น",
      cta_learn: "เรียนรู้เพิ่มเติม",
      track_websites: "เว็บไซต์",
      track_apps: "แอป",
      track_games: "เกม",
      features_title: "ทำไมต้องแพลตฟอร์มของเรา?",
      feature_4_title: "ทดลองใช้",
      feature_4_desc: "3 บทเรียนฟรีเพื่อเริ่มต้น",
      projects_title: "โปรเจคนักเรียน",
      view_project: "ดูโปรเจค",
    },
  },
  vi: { // Vietnamese
    nav: {
      home: "Trang chủ",
      courses: "Khóa học",
      projects: "Dự án",
      profile: "Hồ sơ",
      login: "Đăng nhập",
      logout: "Đăng xuất",
    },
    home: {
      hero_title: "Học tạo với AI",
      hero_subtitle: "Tạo website, ứng dụng và game với trí tuệ nhân tạo",
      cta_start: "Bắt đầu",
      cta_learn: "Tìm hiểu thêm",
      track_websites: "Website",
      track_apps: "Ứng dụng",
      track_games: "Trò chơi",
      features_title: "Tại sao chọn nền tảng của chúng tôi?",
      feature_4_title: "Truy cập dùng thử",
      feature_4_desc: "3 bài học miễn phí để bắt đầu",
      projects_title: "Dự án sinh viên",
      view_project: "Xem dự án",
    },
  },
  id: { // Indonesian
    nav: {
      home: "Beranda",
      courses: "Kursus",
      projects: "Proyek",
      profile: "Profil",
      login: "Masuk",
      logout: "Keluar",
    },
    home: {
      hero_title: "Belajar membuat dengan AI",
      hero_subtitle: "Buat website, aplikasi, dan game dengan kecerdasan buatan",
      cta_start: "Mulai",
      cta_learn: "Pelajari lebih lanjut",
      track_websites: "Website",
      track_apps: "Aplikasi",
      track_games: "Game",
      features_title: "Mengapa platform kami?",
      feature_4_title: "Akses percobaan",
      feature_4_desc: "3 pelajaran gratis untuk memulai",
      projects_title: "Proyek siswa",
      view_project: "Lihat proyek",
    },
  },
};

// Add missing sections to all languages
Object.keys(additionalLanguages).forEach((lang) => {
  const langData = (additionalLanguages as any)[lang];
  
  // Add missing home keys
  if (langData.home && !langData.home.badge_text) {
    langData.home.badge_text = "Learn in 2-3 days · Create with AI";
  }
  if (langData.home && !langData.home.tracks_title) {
    langData.home.tracks_title = "Choose Your Path";
  }
  
  // Add missing sections with English fallbacks
  if (!langData.courses) {
    langData.courses = {
      title: "Choose Your Learning Path",
      levels: "levels",
      start: "Start",
      continue: "Continue",
      locked: "Locked",
      path_title: "Developer Path",
      subtitle: "Full course from zero to pro with",
      create_with: "Create",
      websites: "websites",
      games: "games",
      apps: "apps",
      without_code: "without coding knowledge",
      lesson: "Lesson",
      free_lesson: "Free",
      locked_lesson: "Paid Lesson",
      locked_desc: "This lesson is available after purchasing the course for $100",
      complete_free: "Complete free lessons, then buy full access!",
    };
  }
  if (!langData.profile) {
    langData.profile = {
      title: "Profile",
      progress: "Learning Progress",
      completed: "Levels Completed",
      achievements: "Achievements",
      stats: "Statistics",
      lessons_completed: "Lessons Completed",
      progress_percent: "Progress",
      days_learning: "Days Learning",
      remaining: "Remaining",
      your_progress: "Your Progress",
      continue_learning: "Continue",
      first_step: "First Step",
      complete_1: "Complete 1 lesson",
      beginner: "Beginner",
      complete_10: "Complete 10 lessons",
      expert: "Expert",
      complete_50: "Complete 50 lessons",
      master: "Master",
      complete_all: "Complete all lessons",
      next_goal: "Next Goal",
      start_course: "Start Course",
      joined: "Joined",
      student_status: "Student",
      developer_status: "Developer",
      expert_status: "Expert",
      master_status: "Master",
    };
  }
  if (!langData.payment) {
    langData.payment = {
      title: "Get access to all lessons!",
      subtitle: "Create websites, games, apps with AI",
      special_offer: "Special Offer",
      discount_ends: "33% discount ending soon (save $50)",
      buy_discount: "Buy with Discount",
      buy_course: "Buy Course",
      save_money: "Save $50",
      regular_price: "Regular Price",
      hurry_discount: "Hurry to buy with discount!",
      whats_included: "What's Included:",
      full_course: "Full Course",
      course_desc: "From setup to project deployment",
      any_programs: "Create Any Programs",
      programs_desc: "Websites, games, applications",
      fast_learning: "Learn in 2-3 Days",
      intensive: "Intensive program",
      work_ai: "Work with AI",
      ai_desc: "Write in English - AI creates code",
      lifetime: "Lifetime Access",
      lifetime_desc: "Pay once, access forever",
      support: "24/7 Support",
      support_desc: "We answer all questions",
      great_choice: "Great Choice!",
      get_access: "You'll get full access to all lessons",
      discount_33: "33% Discount:",
      total: "Total:",
      lifetime_access: "Lifetime access to all lessons",
      instant_activation: "Instant activation after payment",
      secure_payment: "100% secure payment",
      pay_button: "Pay $100",
      pay_instant: "By clicking the button, you'll get instant access to all lessons",
    };
  }
  if (!langData.auth) {
    langData.auth = { login_title: "Login", email_placeholder: "Email", code_placeholder: "Code", send_code: "Send", verify: "Verify", code_sent: "Sent" };
  }
  if (!langData.footer) {
    langData.footer = { description: "Platform description", links: "Links", about: "About", contact: "Contact", privacy: "Privacy" };
  }
});
