// Additional languages - 7 languages
export const additionalLanguages = {
  de: { nav: { home: "Startseite", courses: "Kurse", projects: "Projekte", profile: "Profil", login: "Anmelden", logout: "Abmelden" }, home: { badge_text: "Lerne mit KI", hero_title: "Lerne mit KI zu erstellen", hero_subtitle: "Erstelle Websites, Apps und Spiele", cta_start: "Starten", cta_learn: "Mehr", tracks_title: "Wähle deinen Weg", track_websites: "Websites", track_apps: "Apps", track_games: "Spiele", features_title: "Warum unsere Plattform?", projects_title: "Studentenprojekte", view_project: "Projekt ansehen" } },
  nl: { nav: { home: "Home", courses: "Cursussen", projects: "Projecten", profile: "Profiel", login: "Inloggen", logout: "Uitloggen" }, home: { badge_text: "Leer met AI", hero_title: "Leer creëren met AI", hero_subtitle: "Maak websites, apps en games", cta_start: "Beginnen", cta_learn: "Meer", tracks_title: "Kies je pad", track_websites: "Websites", track_apps: "Apps", track_games: "Spellen", features_title: "Waarom ons platform?", projects_title: "Studentenprojecten", view_project: "Bekijk project" } },
  pl: { nav: { home: "Strona główna", courses: "Kursy", projects: "Projekty", profile: "Profil", login: "Zaloguj", logout: "Wyloguj" }, home: { badge_text: "Naucz się z AI", hero_title: "Naucz się tworzyć z AI", hero_subtitle: "Twórz strony, aplikacje i gry", cta_start: "Rozpocznij", cta_learn: "Więcej", tracks_title: "Wybierz ścieżkę", track_websites: "Strony", track_apps: "Aplikacje", track_games: "Gry", features_title: "Dlaczego nasza platforma?", projects_title: "Projekty studentów", view_project: "Zobacz projekt" } },
  ro: { nav: { home: "Acasă", courses: "Cursuri", projects: "Proiecte", profile: "Profil", login: "Conectare", logout: "Deconectare" }, home: { badge_text: "Învață cu AI", hero_title: "Învață să creezi cu AI", hero_subtitle: "Creează site-uri, aplicații și jocuri", cta_start: "Începe", cta_learn: "Mai mult", tracks_title: "Alege calea", track_websites: "Site-uri", track_apps: "Aplicații", track_games: "Jocuri", features_title: "De ce platforma noastră?", projects_title: "Proiecte studenți", view_project: "Vezi proiectul" } },
  hu: { nav: { home: "Főoldal", courses: "Tanfolyamok", projects: "Projektek", profile: "Profil", login: "Bejelentkezés", logout: "Kijelentkezés" }, home: { badge_text: "Tanulj AI-val", hero_title: "Tanulj alkotni AI-val", hero_subtitle: "Készíts weboldalakat, alkalmazásokat és játékokat", cta_start: "Kezdés", cta_learn: "Több", tracks_title: "Válaszd az utad", track_websites: "Weboldalak", track_apps: "Alkalmazások", track_games: "Játékok", features_title: "Miért platformunk?", projects_title: "Diák projektek", view_project: "Projekt megtekintése" } },
  fr: { nav: { home: "Accueil", courses: "Cours", projects: "Projets", profile: "Profil", login: "Connexion", logout: "Déconnexion" }, home: { badge_text: "Apprends avec l'IA", hero_title: "Apprends à créer avec l'IA", hero_subtitle: "Crée des sites, des apps et des jeux", cta_start: "Commencer", cta_learn: "En savoir plus", tracks_title: "Choisis ton chemin", track_websites: "Sites web", track_apps: "Applications", track_games: "Jeux", features_title: "Pourquoi notre plateforme?", projects_title: "Projets étudiants", view_project: "Voir le projet" } },
  es: { nav: { home: "Inicio", courses: "Cursos", projects: "Proyectos", profile: "Perfil", login: "Iniciar sesión", logout: "Cerrar sesión" }, home: { badge_text: "Aprende con IA", hero_title: "Aprende a crear con IA", hero_subtitle: "Crea sitios web, apps y juegos", cta_start: "Empezar", cta_learn: "Saber más", tracks_title: "Elige tu camino", track_websites: "Sitios web", track_apps: "Aplicaciones", track_games: "Juegos", features_title: "¿Por qué nuestra plataforma?", projects_title: "Proyectos de estudiantes", view_project: "Ver proyecto" } },
};
