import { Sparkles, Code, Smartphone, Gamepad2, Layers, FileCode, Palette, Zap, Boxes, Globe, Settings, Terminal, GitBranch, Database, Lock, CreditCard, TrendingUp, Layout, Monitor } from "lucide-react";

export interface Level {
  id: number;
  title: string;
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  topics: string[];
  category: "foundation" | "html" | "css" | "javascript" | "games" | "react" | "advanced";
  icon: any;
  blockName?: string;
}

// 🌊 ПОЛНЫЙ КУРС "СОЗДАВАЙ С WINDSURF" - 220 УРОКОВ
export const allCourseLevels: Level[] = [
  
  // 🚀 БЛОК 1: ЗНАКОМСТВО С WINDSURF (Уроки 1-20)
  {
    id: 1,
    title: "Добро пожаловать! Что тебя ждёт",
    description: "О курсе: 220 уроков от нуля до создания любых проектов. Без кода, только с AI",
    difficulty: "beginner",
    topics: ["О курсе", "Что создашь", "План обучения"],
    category: "foundation",
    icon: Sparkles,
    blockName: "Знакомство с Windsurf"
  },
  {
    id: 2,
    title: "Что такое Windsurf",
    description: "Редактор кода со встроенным AI. Ты пишешь текст - AI создаёт код",
    difficulty: "beginner",
    topics: ["Windsurf", "AI внутри", "Возможности"],
    category: "foundation",
    icon: Code,
  },
  {
    id: 3,
    title: "Чем Windsurf лучше других",
    description: "VS Code + ChatGPT в одном. Не нужно переключаться между окнами",
    difficulty: "beginner",
    topics: ["Сравнение", "Преимущества", "Почему Windsurf"],
    category: "foundation",
    icon: TrendingUp,
  },
  {
    id: 4,
    title: "Что можно создать с Windsurf",
    description: "Сайты, игры, приложения, боты - всё что угодно. Примеры готовых проектов",
    difficulty: "beginner",
    topics: ["Примеры", "Возможности", "Вдохновение"],
    category: "foundation",
    icon: Sparkles,
  },
  {
    id: 5,
    title: "Скачай и установи Windsurf",
    description: "📥 https://codeium.com/windsurf → Скачай → Установи → Открой",
    difficulty: "beginner",
    topics: ["Установка", "Первый запуск"],
    category: "foundation",
    icon: Settings,
  },
  {
    id: 6,
    title: "Экскурсия по интерфейсу",
    description: "Слева файлы, в центре код, справа AI чат. Где что находится",
    difficulty: "beginner",
    topics: ["Интерфейс", "Панели", "Навигация"],
    category: "foundation",
    icon: Layout,
  },
  {
    id: 7,
    title: "Создай свою первую папку",
    description: "File → Open Folder → Создай папку my-first-project → Открой в Windsurf",
    difficulty: "beginner",
    topics: ["Папки", "Проект", "Организация"],
    category: "foundation",
    icon: FileCode,
  },
  {
    id: 8,
    title: "Создай первый файл",
    description: "Клик правой кнопкой → New File → index.html. Твой первый файл готов!",
    difficulty: "beginner",
    topics: ["Файлы", "HTML", "Создание"],
    category: "foundation",
    icon: FileCode,
  },
  {
    id: 9,
    title: "Открой чат с AI (Ctrl+L)",
    description: "Нажми Ctrl+L (Cmd+L на Mac) - откроется чат справа. Это твой AI помощник",
    difficulty: "beginner",
    topics: ["Чат", "Горячие клавиши", "AI"],
    category: "foundation",
    icon: Sparkles,
  },
  {
    id: 10,
    title: "Выбери AI модель",
    description: "Claude Sonnet 4.5 - ЛУЧШАЯ для кода. Выбери её в выпадающем списке",
    difficulty: "beginner",
    topics: ["Модели", "Claude", "Настройка"],
    category: "foundation",
    icon: Settings,
  },
  {
    id: 11,
    title: "Файловая система",
    description: "index.html, style.css, script.js, папка images/",
    difficulty: "beginner",
    topics: ["Структура", "Организация", "Best practices"],
    category: "foundation",
    icon: FileCode,
  },
  {
    id: 12,
    title: "Live Preview",
    description: "💬 Промпт: 'Установи расширение Live Server. Покажи как запустить' | Или открой HTML файл в браузере",
    difficulty: "beginner",
    topics: ["Расширения", "Автообновление", "Превью"],
    category: "foundation",
    icon: Monitor,
  },
  {
    id: 13,
    title: "Терминал в Windsurf",
    description: "Ctrl+`, базовые команды, установка пакетов",
    difficulty: "beginner",
    topics: ["Terminal", "Команды", "npm"],
    category: "foundation",
    icon: Terminal,
  },
  {
    id: 14,
    title: "Экспорт/сохранение чата",
    description: "Export Chat, сохранить как .txt или .md, история",
    difficulty: "beginner",
    topics: ["Экспорт", "Сохранение", "История"],
    category: "foundation",
    icon: FileCode,
  },
  {
    id: 15,
    title: "ПРОЕКТ: Первая страница",
    description: "От идеи до публикации с Windsurf AI",
    difficulty: "beginner",
    topics: ["Проект", "HTML", "Публикация"],
    category: "foundation",
    icon: Sparkles,
  },

  // 💻 БЛОК 2: HTML С WINDSURF (Уроки 16-35)
  {
    id: 16,
    title: "Попроси AI объяснить HTML",
    description: "💬 Промпт: 'Объясни что такое HTML простыми словами. Покажи примеры основных тегов'",
    difficulty: "beginner",
    topics: ["HTML основы", "Теги", "Структура"],
    category: "html",
    icon: Code,
    blockName: "HTML с Windsurf"
  },
  {
    id: 17,
    title: "Структура HTML документа",
    description: "<!DOCTYPE>, <html>, <head>, <body>",
    difficulty: "beginner",
    topics: ["Структура", "Обязательные теги"],
    category: "html",
    icon: FileCode,
  },
  {
    id: 18,
    title: "Заголовки H1-H6",
    description: "💬 Промпт: 'Создай страницу с 3 заголовками H1, H2, H3. H1 красный, H2 синий, H3 зелёный'",
    difficulty: "beginner",
    topics: ["Заголовки", "Иерархия"],
    category: "html",
    icon: Code,
  },
  {
    id: 19,
    title: "Абзацы и текст",
    description: "Теги <p>, <br>, <strong>, <em>",
    difficulty: "beginner",
    topics: ["Текст", "Форматирование"],
    category: "html",
    icon: FileCode,
  },
  {
    id: 20,
    title: "Ссылки и навигация",
    description: "💬 Промпт: 'Добавь 3 ссылки: на Google (новая вкладка), на страницу about.html, и якорную ссылку вниз'",
    difficulty: "beginner",
    topics: ["Ссылки", "Навигация", "target"],
    category: "html",
    icon: Globe,
  },
  {
    id: 21,
    title: "Изображения",
    description: "💬 Промпт: 'Добавь картинку с Unsplash (https://source.unsplash.com/800x600/?nature) шириной 400px'",
    difficulty: "beginner",
    topics: ["Картинки", "Оптимизация"],
    category: "html",
    icon: FileCode,
  },
  {
    id: 22,
    title: "Списки",
    description: "Маркированные <ul> и нумерованные <ol>",
    difficulty: "beginner",
    topics: ["Списки", "Вложенность"],
    category: "html",
    icon: Code,
  },
  {
    id: 23,
    title: "Таблицы",
    description: "Создай таблицу 3x3, стилизация",
    difficulty: "beginner",
    topics: ["Таблицы", "Строки", "Ячейки"],
    category: "html",
    icon: Boxes,
  },
  {
    id: 24,
    title: "Формы - часть 1",
    description: "<form>, <input>, <button>",
    difficulty: "beginner",
    topics: ["Формы", "Поля ввода"],
    category: "html",
    icon: FileCode,
  },
  {
    id: 25,
    title: "Формы - часть 2",
    description: "textarea, select, checkbox, radio",
    difficulty: "beginner",
    topics: ["Расширенные поля", "Валидация"],
    category: "html",
    icon: Code,
  },
  {
    id: 26,
    title: "Семантические теги",
    description: "header, nav, main, footer, article, section",
    difficulty: "intermediate",
    topics: ["Семантика", "Доступность", "SEO"],
    category: "html",
    icon: Layout,
  },
  {
    id: 27,
    title: "Мета-теги",
    description: "SEO мета-теги, Open Graph для соцсетей",
    difficulty: "intermediate",
    topics: ["SEO", "Meta", "OG"],
    category: "html",
    icon: TrendingUp,
  },
  {
    id: 28,
    title: "Favicon",
    description: "📥 Генератор: https://favicon.io | 💬 Промпт: 'Подключи favicon.ico в head секцию'",
    difficulty: "beginner",
    topics: ["Favicon", "Icons"],
    category: "html",
    icon: Sparkles,
  },
  {
    id: 29,
    title: "Видео и аудио",
    description: "YouTube embed, HTML5 video и audio",
    difficulty: "beginner",
    topics: ["Медиа", "Встраивание"],
    category: "html",
    icon: Monitor,
  },
  {
    id: 30,
    title: "Iframe и встраивание",
    description: "💬 Промпт: 'Встрой Google Maps с адресом Киев, Крещатик. Добавь YouTube видео'",
    difficulty: "beginner",
    topics: ["Iframe", "Maps", "Embed"],
    category: "html",
    icon: Globe,
  },
  {
    id: 31,
    title: "ПРОЕКТ: Главная страница",
    description: "Полноценная главная с навигацией",
    difficulty: "intermediate",
    topics: ["Проект", "Практика"],
    category: "html",
    icon: Sparkles,
  },
  {
    id: 32,
    title: "ПРОЕКТ: Страница О нас",
    description: "История, команда, ценности",
    difficulty: "intermediate",
    topics: ["Контент", "Структура"],
    category: "html",
    icon: Code,
  },
  {
    id: 33,
    title: "ПРОЕКТ: Страница Услуги",
    description: "Карточки услуг, описания",
    difficulty: "intermediate",
    topics: ["Услуги", "Layout"],
    category: "html",
    icon: Boxes,
  },
  {
    id: 34,
    title: "ПРОЕКТ: Страница Контакты",
    description: "Форма, карта, контактная информация",
    difficulty: "intermediate",
    topics: ["Контакты", "Формы", "Maps"],
    category: "html",
    icon: Globe,
  },
  {
    id: 35,
    title: "ПРОЕКТ: Многостраничный сайт",
    description: "Связывание всех страниц, навигация",
    difficulty: "intermediate",
    topics: ["Навигация", "Структура", "Links"],
    category: "html",
    icon: Sparkles,
  },

  // 🎨 БЛОК 3: CSS С WINDSURF (Уроки 36-70)
  {
    id: 36,
    title: "Способы подключения CSS",
    description: "Inline, <style>, внешний файл style.css",
    difficulty: "beginner",
    topics: ["CSS подключение", "Best practices"],
    category: "css",
    icon: Palette,
    blockName: "CSS с Windsurf"
  },
  {
    id: 37,
    title: "Селекторы CSS",
    description: "По тегу, классу, ID. Разница и применение",
    difficulty: "beginner",
    topics: ["Селекторы", "Специфичность"],
    category: "css",
    icon: Code,
  },
  {
    id: 38,
    title: "Цвета в CSS",
    description: "Названия, HEX, RGB, HSL, градиенты",
    difficulty: "beginner",
    topics: ["Цвета", "Градиенты", "Прозрачность"],
    category: "css",
    icon: Palette,
  },
  {
    id: 39,
    title: "Шрифты",
    description: "📥 Google Fonts: https://fonts.google.com | 💬 Промпт: 'Подключи шрифт Roboto и примени к body'",
    difficulty: "beginner",
    topics: ["Шрифты", "Typography"],
    category: "css",
    icon: FileCode,
  },
  {
    id: 40,
    title: "Блочная модель",
    description: "Content, Padding, Border, Margin",
    difficulty: "beginner",
    topics: ["Box Model", "Отступы"],
    category: "css",
    icon: Boxes,
  },

  // Продолжение CSS блока (41-70)
  ...Array.from({ length: 30 }, (_, i) => ({
    id: 41 + i,
    title: `CSS урок ${41 + i}`,
    description: `Flexbox, Grid, анимации, адаптивность`,
    difficulty: (i < 10 ? "beginner" : i < 20 ? "intermediate" : "advanced") as "beginner" | "intermediate" | "advanced",
    topics: ["CSS", "Практика"],
    category: "css" as const,
    icon: Palette,
  })),

  // ⚡ БЛОК 4: JAVASCRIPT (Уроки 71-120)
  ...Array.from({ length: 50 }, (_, i) => ({
    id: 71 + i,
    title: `JavaScript урок ${71 + i}`,
    description: `Переменные, функции, DOM, API, проекты`,
    difficulty: (i < 15 ? "beginner" : i < 35 ? "intermediate" : "advanced") as "beginner" | "intermediate" | "advanced",
    topics: ["JavaScript", "Интерактивность"],
    category: "javascript" as const,
    icon: Zap,
    blockName: i === 0 ? "JavaScript с Windsurf" : undefined,
  })),

  // 🎮 БЛОК 5: ИГРЫ (Уроки 121-160)
  ...Array.from({ length: 40 }, (_, i) => ({
    id: 121 + i,
    title: `Игры урок ${121 + i}`,
    description: `Canvas, анимации, игровая логика, Phaser`,
    difficulty: (i < 10 ? "beginner" : i < 25 ? "intermediate" : "advanced") as "beginner" | "intermediate" | "advanced",
    topics: ["Игры", "Canvas", "Анимации"],
    category: "games" as const,
    icon: Gamepad2,
    blockName: i === 0 ? "Создание игр" : undefined,
  })),

  // 🚀 БЛОК 6: REACT (Уроки 161-200)
  ...Array.from({ length: 40 }, (_, i) => ({
    id: 161 + i,
    title: `React урок ${161 + i}`,
    description: `Компоненты, hooks, роутинг, большие проекты`,
    difficulty: (i < 10 ? "intermediate" : "advanced") as "beginner" | "intermediate" | "advanced",
    topics: ["React", "Hooks", "Components"],
    category: "react" as const,
    icon: Layers,
    blockName: i === 0 ? "React и приложения" : undefined,
  })),

  // 🎁 БЛОК 7: ПРОДВИНУТОЕ (Уроки 201-220)
  ...Array.from({ length: 20 }, (_, i) => ({
    id: 201 + i,
    title: `Продвинутое ${201 + i}`,
    description: `Git, Firebase, монетизация, карьера`,
    difficulty: "advanced" as const,
    topics: ["Git", "Деплой", "Карьера"],
    category: "advanced" as const,
    icon: TrendingUp,
    blockName: i === 0 ? "Продвинутые темы" : undefined,
  })),
];
